### ISSUE TITLE
timers in alt.

### ISSUE THREAD

**Issue by mattunlv** [mattunlv/ProcessJ#12]
Timers in alts are not correctly started when there are timeouts in alts.

public void main(string args[]) {
       timer t;
       long now;
       now = t.read();
       t.timeout(t.read()+2000);
       println("Hello World!");
       now = t.read();
       int x;
       chan<int> c;
       alt {
         x = c.read() : skip;
         t.timeout(now+2000) : println("Alt timed out");
       }
}

the timeout outside the alt generates:

            _ld$now2 = PJTimer.read();
            _ld$tmp0$3 = _ld$t1;
            _ld$tmp2$5 = PJTimer.read();
            _ld$tmp1$4 = _ld$tmp2$5 + 2000;
            _ld$tmp0$3 = new PJTimer(this, _ld$tmp1$4);
            try {
                _ld$tmp0$3.start();
                this.setNotReady();
                this.runLabel = 1;
                this.yield();
            } catch (InterruptedException e) {
                System.out.println("An Interrupted exception occurred for a timer!");
            }

but the one inside:

            _ld$now2 = PJTimer.read();
            _ld$c7 = new PJOne2OneChannel();
            _ld$alt9 = new PJAlt(2, this);
            _ld$t1 = new PJTimer(this, _ld$now2 + 2000);

is it missing:

 try {
                _ld$t1.start();
            } catch (InterruptedException e) {
                System.out.println("An Interrupted exception occurred for a timer!");
            }

**Comment by ninjabox77** [comment]
My version already takes care of this issue :)

**Comment by ninjabox77** [comment]
this was fixed in my version
