### ISSUE TITLE
"Record" is not recognized symbol, though is listed on page 152 of the book. Also, records and protocols cannot contain members of the same type?

### ISSUE THREAD

**Issue by jamespiotrowski** [mattunlv/ProcessJ#7]
Hello, 
I need to pass messages through channels in which the messages may contain different data. The thing is, the message may need to carry a channel end of the same message type. Something like:

```
public record message{
    channel<message>.write out;
}
```
This does not work with records. So I attempted extensions. 
```
public record message{
    char messageType;
}

public record channelMessage extends message{
    chan<message>.write out;
}
```
It does not like that either. 

Finally, I tried protocols. Something like:
```
public protocol message{
    chnl: { channel<message>.write out; }
    msg: { int m; }
    kill: { }
}
```
I get the same (or similar) error that I did with the records above. I then tried some protocol extending shenanigans and I did not get very far. 

So it appears neither protocols nor records can contain members of the same type.

My final solution was to use the "Record" super class type referenced on page 152. 
```
public record message{
    channel<Record>.write out;
}
```
Though "Record" is not a recognized symbol.

Questions: 
(1) Is it intended that records and protocols cannot contain members of the same type?
(2) Is "Record" supposed to be usable?

**Comment by clcuenca** [comment]
Do you have a full sample you can send over?

I can take a look at it after class later on tonight;

**Comment by jamespiotrowski** [comment]
There should be 4 things in there that generate errors.

The record, the extended record, the record with "Record" in it, and then
the "Record" in main.


JP

**Comment by jamespiotrowski** [comment]
[PassingMsgs.txt](https://github.com/mattunlv/ProcessJ/files/9963038/PassingMsgs.txt)

**Comment by jamespiotrowski** [comment]
Sorry, the .pj file was rejected last night. Attached is a text file.

**Comment by clcuenca** [comment]
Thank you, looking at it now.

It looks like the issue is with the code generation, this might just be a simple fix.

**Comment by clcuenca** [comment]
@jamespiotrowski Pull and try it now.

Let me know if there are any other issues; if everything is ok I'll close this by the end of today.

**Comment by jamespiotrowski** [comment]
The txt file I attached is still not compiling. Also, arrays work differently than before? Please try to compile this code attached. 
[Arrays.txt](https://github.com/mattunlv/ProcessJ/files/9966566/Arrays.txt)

**Comment by jamespiotrowski** [comment]
After testing last night, records can now contain members of the same type. Thank you. 

"Record" still does not work, but because you fixed the other thing, I can move forward. 

I'm still having trouble with arrays though.

**Comment by clcuenca** [comment]
Yes, I went back and checked. 

There are some discrepancies with the types and I was combing over them last night (til 4am <:^) )

I'll get a patch out as soon as possible.

**Comment by jamespiotrowski** [comment]
Arrays seem to be working again. This issue can be closed.
